### ISSUE TITLE
DB builder运行出错

### ISSUE THREAD

**Issue by songjinghe** [songjinghe/gephi-plugins-1#1]
```
java.lang.IllegalAccessError: tried to access class com.google.common.base.Platform from class com.google.common.base.Ticker$1
	at com.google.common.base.Ticker$1.read(Ticker.java:60)
	at com.google.common.base.Stopwatch.start(Stopwatch.java:162)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3523)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.act.temporalProperty.impl.TableCache.getTable(TableCache.java:63)
	at org.act.temporalProperty.table.MergeProcess$MergeTask.getDataIterator(MergeProcess.java:283)
	at org.act.temporalProperty.table.MergeProcess$MergeTask.runTask(MergeProcess.java:342)
	at org.act.temporalProperty.table.MergeProcess.startMergeProcess(MergeProcess.java:144)
[catch] at org.act.temporalProperty.table.MergeProcess.run(MergeProcess.java:82)
```
我怀疑是不是用到了相同的maven包但是版本不一致。

**Comment by songjinghe** [comment]
`CacheBuilder`在temporal-property-store包里用的是guava18.0版本。而在IDE中确实发现了16.0.1版本的guava，但是无法定位是那个模块使用了这个包。

**Comment by songjinghe** [comment]
用`mvn dependency:tree`在Kernel里面有个叫jimfs的包（这个包的scope是test），这个包引用了guava，但没写版本，估计是16.0.1了。另外aliyun的log-producer包也用到了guava，但是版本是什么27-jre很奇葩，我把log-producer去掉后还是会报同样的错。

但是如果直接用Kernel写的话会报错吗？报错的线程是后台的merge线程。

**Comment by songjinghe** [comment]
这种情况通常是因为在运行时引入了多个不同版本的类（来自不同的jar包）。比如在某个版本的`com.google.common.base.Platform`类不是public的就会出这个错误。

在intellij idea中搜索Platform类，找到三个全称为`com.google.common.base.Platform`的，分别在guava16.0.1， guava18.0，google-collections1.0这三个包里。然后在gephi-demo文件夹中运行`mvn dependency:tree`发现其`org.gephi:core-library-wrapper:jar:0.9.1`这个包用到了`com.google.collections:google-collections:jar:1.0`这个包。怀疑是这个包导致了异常。（这也可以解释为什么不在gephi中运行就没错）

至于解决的办法么，`google-collections`这个包就是后来的guava包。怀疑是gephi里代码太老了，没有更新这个依赖。那么解决方法有两个，一个是去看下gephi0.9.2是否有更新这个包，如果有的话把gephi-demo升级到0.9.2即可。否则的话就是回去查看一下2016年那个demo版本为啥没有异常，用的是哪个版本，看能不能切回去。。。

**Comment by songjinghe** [comment]
去Maven上搜了一下：
https://search.maven.org/artifact/org.gephi/core-library-wrapper/0.9.2/nbm
https://search.maven.org/artifact/org.gephi/core-library-wrapper/0.9.1/nbm
发现确实0.9.2的时候去掉了这个包。ok所以我们可以升级一下demo用的gephi版本。

**Comment by songjinghe** [comment]
升级后没有这个问题，可以正常build数据库了。
